  server:
   port: 8000


  eureka:
    client:
      register-with-eureka: true     #表示是否将自己注册进EurekaServer默认为true
      fetch-registry: true   #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/

  spring:
    application:
      name: cloud-provider-hystrix-order

  ribbon:
    ReadTimeout:  5000 #读取资源所用时间
    ConnectTimeout: 5000  #建立连接时间

  feign:
    hystrix:
      enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。


